### ISSUE TITLE
CCF推荐期刊会议更名

### ISSUE THREAD

**Issue by Dorence** [ciaranchen/utools-thesis-tools#1]
- CCF通知：https://www.ccf.org.cn/Academic_Evaluation/By_category/
- 更新后csv：[Dornece/utools-thesis-toos > 50cc905 > ccf-2022-en.csv](https://github.com/Dorence/utools-thesis-tools/blob/50cc905624a0ec451d6150da1330969f656bbdd9/assets/ccf-2022-en.csv)

**Comment by ciaranchen** [comment]
已合并，并在utools应用市场更新。
